cat << EOF > ./apps/tp-app/.env.local
VITE_APIKEY=$VITE_APIKEY
VITE_APPID=$VITE_APPID
VITE_AUTHDOMAIN=$VITE_AUTHDOMAIN
VITE_PROJECTID=$VITE_PROJECTID
VITE_STORAGEBUCKET=$VITE_STORAGEBUCKET
VITE_MESSAGINGSENDERID=$VITE_MESSAGINGSENDERID
VITE_MEASUREMENTID=$VITE_MEASUREMENTID
VITE_DATABASEURL=$VITE_DATABASEURL
EOF