/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TpCanvas {
        "backupPaths": () => Promise<string>;
        "exportDrawing": () => Promise<Blob>;
        "height": number;
        "hostEl": HTMLElement;
        "restoreBackup": (pathsString: any) => Promise<void>;
        "width": number;
    }
    interface TpCanvasControls {
        "hostEl": HTMLElement;
        "submithandler": (e:Event)=>void;
    }
    interface TpContent {
        "content": string;
        "type": string;
    }
    interface TpIcon {
        "icon": any;
    }
    interface TpInputZone {
        "characterLimit": number;
        "round": number;
        "sendingTo": string;
    }
    interface TpModal {
        "contentType": string;
        "enabled": boolean;
        "store": any;
    }
    interface TpReviewChat {
        "showAll": any;
        "stackProxy": any;
    }
    interface TpTimeInput {
        "initialValue": any;
        "maxMinutes": any;
        "maxSeconds": any;
        "placeholder": any;
        "timeError": string;
        "value": number;
    }
    interface TpTimer {
        "endtime": number;
    }
}
declare global {
    interface HTMLTpCanvasElement extends Components.TpCanvas, HTMLStencilElement {
    }
    var HTMLTpCanvasElement: {
        prototype: HTMLTpCanvasElement;
        new (): HTMLTpCanvasElement;
    };
    interface HTMLTpCanvasControlsElement extends Components.TpCanvasControls, HTMLStencilElement {
    }
    var HTMLTpCanvasControlsElement: {
        prototype: HTMLTpCanvasControlsElement;
        new (): HTMLTpCanvasControlsElement;
    };
    interface HTMLTpContentElement extends Components.TpContent, HTMLStencilElement {
    }
    var HTMLTpContentElement: {
        prototype: HTMLTpContentElement;
        new (): HTMLTpContentElement;
    };
    interface HTMLTpIconElement extends Components.TpIcon, HTMLStencilElement {
    }
    var HTMLTpIconElement: {
        prototype: HTMLTpIconElement;
        new (): HTMLTpIconElement;
    };
    interface HTMLTpInputZoneElement extends Components.TpInputZone, HTMLStencilElement {
    }
    var HTMLTpInputZoneElement: {
        prototype: HTMLTpInputZoneElement;
        new (): HTMLTpInputZoneElement;
    };
    interface HTMLTpModalElement extends Components.TpModal, HTMLStencilElement {
    }
    var HTMLTpModalElement: {
        prototype: HTMLTpModalElement;
        new (): HTMLTpModalElement;
    };
    interface HTMLTpReviewChatElement extends Components.TpReviewChat, HTMLStencilElement {
    }
    var HTMLTpReviewChatElement: {
        prototype: HTMLTpReviewChatElement;
        new (): HTMLTpReviewChatElement;
    };
    interface HTMLTpTimeInputElement extends Components.TpTimeInput, HTMLStencilElement {
    }
    var HTMLTpTimeInputElement: {
        prototype: HTMLTpTimeInputElement;
        new (): HTMLTpTimeInputElement;
    };
    interface HTMLTpTimerElement extends Components.TpTimer, HTMLStencilElement {
    }
    var HTMLTpTimerElement: {
        prototype: HTMLTpTimerElement;
        new (): HTMLTpTimerElement;
    };
    interface HTMLElementTagNameMap {
        "tp-canvas": HTMLTpCanvasElement;
        "tp-canvas-controls": HTMLTpCanvasControlsElement;
        "tp-content": HTMLTpContentElement;
        "tp-icon": HTMLTpIconElement;
        "tp-input-zone": HTMLTpInputZoneElement;
        "tp-modal": HTMLTpModalElement;
        "tp-review-chat": HTMLTpReviewChatElement;
        "tp-time-input": HTMLTpTimeInputElement;
        "tp-timer": HTMLTpTimerElement;
    }
}
declare namespace LocalJSX {
    interface TpCanvas {
        "height"?: number;
        "hostEl"?: HTMLElement;
        "width"?: number;
    }
    interface TpCanvasControls {
        "hostEl"?: HTMLElement;
        "submithandler"?: (e:Event)=>void;
    }
    interface TpContent {
        "content"?: string;
        "type"?: string;
    }
    interface TpIcon {
        "icon"?: any;
    }
    interface TpInputZone {
        "characterLimit"?: number;
        "round"?: number;
        "sendingTo"?: string;
    }
    interface TpModal {
        "contentType"?: string;
        "enabled"?: boolean;
        "store"?: any;
    }
    interface TpReviewChat {
        "showAll"?: any;
        "stackProxy"?: any;
    }
    interface TpTimeInput {
        "initialValue"?: any;
        "maxMinutes"?: any;
        "maxSeconds"?: any;
        "placeholder"?: any;
        "timeError"?: string;
        "value"?: number;
    }
    interface TpTimer {
        "endtime"?: number;
    }
    interface IntrinsicElements {
        "tp-canvas": TpCanvas;
        "tp-canvas-controls": TpCanvasControls;
        "tp-content": TpContent;
        "tp-icon": TpIcon;
        "tp-input-zone": TpInputZone;
        "tp-modal": TpModal;
        "tp-review-chat": TpReviewChat;
        "tp-time-input": TpTimeInput;
        "tp-timer": TpTimer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tp-canvas": LocalJSX.TpCanvas & JSXBase.HTMLAttributes<HTMLTpCanvasElement>;
            "tp-canvas-controls": LocalJSX.TpCanvasControls & JSXBase.HTMLAttributes<HTMLTpCanvasControlsElement>;
            "tp-content": LocalJSX.TpContent & JSXBase.HTMLAttributes<HTMLTpContentElement>;
            "tp-icon": LocalJSX.TpIcon & JSXBase.HTMLAttributes<HTMLTpIconElement>;
            "tp-input-zone": LocalJSX.TpInputZone & JSXBase.HTMLAttributes<HTMLTpInputZoneElement>;
            "tp-modal": LocalJSX.TpModal & JSXBase.HTMLAttributes<HTMLTpModalElement>;
            "tp-review-chat": LocalJSX.TpReviewChat & JSXBase.HTMLAttributes<HTMLTpReviewChatElement>;
            "tp-time-input": LocalJSX.TpTimeInput & JSXBase.HTMLAttributes<HTMLTpTimeInputElement>;
            "tp-timer": LocalJSX.TpTimer & JSXBase.HTMLAttributes<HTMLTpTimerElement>;
        }
    }
}
